DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NOT NULL,
  price_cents SMALLINT NOT NULL DEFAULT 0,
  description TEXT,
  type VARCHAR(255)
);
